name: PR Verification

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  verify:
    name: Verify PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - run: npm ci || npm install

      - run: npm run build

      - run: npm run type-check:strict

      - run: npm run lint

      # Compile TypeScript modules needed for unit tests
      - name: Compile test modules
        run: |
          npx tsc lib/colors.ts --target es2018 --module commonjs --outDir lib --allowJs
          npx tsc lib/unicode.ts --target es2018 --module commonjs --outDir lib --allowJs  
          npx tsc lib/helpers.ts --target es2018 --module commonjs --outDir lib --allowJs

      # Apply cache bug fix to colors.js
      - name: Fix cache bug in colors.js
        run: |
          sed -i 's/!== null/!= null/g' lib/colors.js

      # Run fast unit tests (62 tests in ~700ms)
      - run: npm test
